### ISSUE TITLE
Error resolving plugin 'de.undercouch.download'

### ISSUE THREAD

**Issue by CanRau** [GitJournal/git_bindings#1]
As mentioned on [Twitter](https://twitter.com/Coding4GaiAma/status/1228050223798374400)
I'm getting the following error
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Can/.pub-cache/hosted/pub.dartlang.org/git_bindings-0.0.11/android/build.gradle' line: 13

* What went wrong:
Error resolving plugin [id: 'de.undercouch.download', version: '4.0.0']
> Plugin request for plugin already on the classpath must not include a version

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Gradle task assembleDevDebug failed with exit code 1
Exited (sigterm)
```
just having the plugin in my `pubspec.yaml`, no imports nothing else and it'll crash.

<details>
<summary>Output of <code>flutter doctor -v</code></summary>
<pre><code>
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G1012, locale de-PE)
    • Flutter version 1.12.13+hotfix.8 at /Users/Can/Applications/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Can/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/Can/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • SM N950F            • 988ad045373353304f30 • android-arm64 • Android 9 (API 28)
    • AOSP on IA Emulator • emulator-5554        • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
</code></pre>
</details>

What else could I provide?

**Update:** That happens on Android Emulator (Pixel 3a API 28 Android 9 Pie x86) and on my physical SM N950F (Note 8 running Android 9).
iOS simulator (don't have a physical) builds fine, `GitRepo.init(path)` fails with
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method gitInit on channel gitjournal.io/git)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      invokePlatformMethod (package:git_bindings/git_bindings.dart:13:20)
#2      GitRepo.init (package:git_bindings/git_bindings.dart:40:13)
#3      MainState.didChangeDependencies.<anonymous closure> (package:feder/main.dart:45:17)
<asynchronous suspension>
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/as<…>
```

**update** just updated `minSdkVersion` from `19` to `21` as GitJournal uses, without success tho

**Comment by vHanda** [comment]
I'm not really sure why you're having this issue.

Could you try building just the example of the `git-bindings`? If you still get the error maybe you could try switching in the `build.gradle` file -

```
plugins {
      id "de.undercouch.download" version "4.0.0"
  }
```

for what's mentioned in this bug report? https://github.com/michel-kraemer/gradle-download-task/issues/17

In parallel, I'll try to fast track getting rid of the git_bindings plugin all together. It's causing build issues for others developers as well.

**Comment by vHanda** [comment]
So I started having this issue while building GitJournal in the CI. Bumping the version number of 'de.undercouch.download' seemed to fix it. Can you please check if it now works for you?

**Comment by CanRau** [comment]
I upgraded to 0.0.12 and tried to play with the gradle file in a local fork.
All yield the same issue, only with undercouch version 4.0.4 🤷‍♂️

Yea looking forward to `dart_git` 👍Would love to help yet I'm pretty busy and really new to Dart and Flutter 😭

**Comment by CanRau** [comment]
Forgot to mention that I bootstrapped the project using the Kotlin/Swift starter.

After switching to Java following the steps in this [SO answer](https://stackoverflow.com/a/58602076/3484824) and making sure it works I first got an error stating that I have to bump `minSdkVersion` to `21` after enabling the `git_bindings: 0.0.12` dependency in pubspec.yaml.
After the change it builds forever. Not sure how long I waited or how often I started over, cleaning project, re-starting the emulator but I think I'll have to stop for today^^

Here's my Debug Console output from VSCode
```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
✓ Built build/app/outputs/apk/dev/debug/app-dev-debug.apk.
```

Haven't imported `git_bindings` anywhere so far, it's only in pubspec.yaml.
After commenting the dependecy out, it starts as expected after ~3sec. 🤷‍♂

**Comment by antranapp** [comment]
I have the same problem today when trying to add git_bindings into a new project.
I fixed the problem by solving the exact error stated in the error message 
```
Plugin request for plugin already on the classpath must not include a version
``` 

Go to `~/.pub-cache/hosted/pub.dartlang.org/git_bindings-0.0.12/android/build.gradle` and remove the version number from the `de.undercouch.download` plugin:

```
plugins {
    id "de.undercouch.download"
}
```

No it works. I have no idea why this workaround works.

**Comment by vHanda** [comment]
Sorry. I'm quite clueless as well. That plugin is used to download a tarball with the compiled versions of libgit2 and other required libs. It can also be done manually, you'll just need to put it in the right location and unzip it.

In other news, `dart_git` now supports `git add`. My aim for next week is `git commit`. After that only the following operations will be left - merge / fetch / push / reset. I've already started using `dart_git` in GitJournal code.

**Comment by antranapp** [comment]
@vHanda Such a great news. Looking forward to `dart_git`.

**Comment by hackaugusto** [comment]
I had the same problem with a freshly generated flutter app, removing the version as @antranapp did fixed it for me too. Is there any downside to remove it from [`build.gradle`](https://github.com/GitJournal/git_bindings/blob/bb8eb2ef112f083102548f2f259ba60cd0c19627/android/build.gradle#L12-L14)? (Edit: I meant removing the version only)

As a wild guess, could it be a conflict with [`kotlin-gradle-plugin-1.3.50.`](https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom) which targets version `3.4.3` of the same package?

**Comment by vHanda** [comment]
I'll try it out without the version number and see if it works for me, and accordingly change it.

**Comment by antranapp** [comment]
It works for me with GitJournal when removing the version but then I have problem with other projects and now I have to put it back again. Don't know what is the problem. I would suggest to remove the plugin completely from the gradle file if it is not that important.

**Comment by vHanda** [comment]
The plugin is super important. It's used to download the compiled libraries of libgit2, ssh and openssl. Without that this flutter plugin would be useless.
