### ISSUE TITLE
Adding Remote

### ISSUE THREAD

**Issue by yogeshkumar98103** [GitJournal/git_bindings#4]
Is there a way I can set remote ? What I need is to create a repository using git init, add remote, then add some files and finally push to remote. Currently the only way to set remote is by using git clone. Can you add a method to make this simpler.

**Comment by vHanda** [comment]
Hello. I would recommend using the dart_git library. It has a method to add a remote.

This repo is eventually going to just have a way to push and pull from remotes over ssh, as that part is too much work to implement in Git.

**Comment by vHanda** [comment]
I just checked, and there is no way to add a remote right now -https://github.com/GitJournal/dart_git/blob/master/lib/commands/remote.dart - but it's easy to implement. Feel free to open an issue in that repo, I'll try to get to it ASAP.

**Comment by vHanda** [comment]
It turns out I had implemented addRemote and forgotten about it - https://github.com/GitJournal/dart_git/blob/master/lib/git.dart#L123
